### ISSUE TITLE
🔨 QA 정리

### ISSUE THREAD

**Issue by gengminy** [cocktail-Ohzu/Ohzu-FrontEnd#23]
QA 내용 정리를 위한 이슈입니다
이슈가 생기는대로 이곳에 추가합니다

- [x] 앱스토어 리젝 사유 변경 (등급 성인으로, 스크린샷 디버그 뱃지 제거)
- [x] 플레이스토어 리젝 예상으로 변경 예정
- [x] 검색 페이지 그리드 요소 좌우 크기 남는 이슈
- [x] 검색 페이지 그리드 세로 길이 220 -> 210 (실제 204...)
- [x] 롱티 같이 길이 긴 애들 오른쪽으로 삐죽 튀어나오는 현상
- [x] 앱 시작 로고 1초 정도 애니메이션 띄워주기 -> 올블랙 오쥬 로고 나타났다가 사라지는
- [x] 검색 추천 태그 많이 띄우기
- [x] 아무것도 선택 안했을 때 추천 결과 멘트 수정 + 뷰 props 전달 로직 변경
- [x] 추천 페이지 순서 맛 - 도수 - 무드 - 날씨 - 베이스 - 재료 - 가니쉬 로 변경
- [x] 검색창 해시태그 검색 + 추천 해시태그 클릭 가이드 툴팁 -> 행간 넓히기
- [x] 추천 결과 결과 칵테일이 유사 칵테일에 중복되어 나타나는 것 수정
- [x] 검색창 placeholder 멘트 변경, 사이즈 수정

**Comment by sukyeongs** [comment]
검색할 때 # 을 먼저 써야 태그 검색이 가능하다는건 일반 사용자들이 알기 어려울 것 같다고 생각합니다.
# 으로 태그 검색이 가능하다는 가이드 팝업을 추가하면 좋을 것 같다고 생각했습니다!

![태그 검색](https://user-images.githubusercontent.com/80563849/189468554-d5c2340e-f6de-418f-b3eb-5375ea09cb24.jpeg)

**Comment by gengminy** [comment]
> 검색할 때 # 을 먼저 써야 태그 검색이 가능하다는건 일반 사용자들이 알기 어려울 것 같다고 생각합니다. `\#으로 태그 검색이 가능하다는 가이드` 팝업을 추가하면 좋을 것 같다고 생각합니다:)

검색 창 들어가자마자 팝업을 한번 띄워주면 좋겠다는 말인거죵??

**Comment by sukyeongs** [comment]
@gengminy 넵 맞습니다!

**Comment by sukyeongs** [comment]
추천페이지에서 유저가 아무것도 선택하지 않았을 때의 로직이 일치하는 칵테일이 없을 때의 경우랑 같아서 그런지
**상단에 뜨는 멘트('일치하는 검색 결과가 없어요. 유사한 칵테일을 추천해드릴게요!')**도 똑같아서
조금 어색하게 느껴지는 것 같습니다! 이것도 회의에서 얘기해보면 좋을 것 같아욥

**Comment by ssssujini99** [comment]
"맛" 태그는 가장 중요하다고 생각하는데 (칵테일의 맛)
그래서 맛은 최대한 많이 띄우는 건 어떻게 생각하나용?

<img width="357" alt="image" src="https://user-images.githubusercontent.com/71487608/189534768-7dd2c9ea-a9b8-45ca-95f5-522c8bfa61a8.png">

**Comment by ssssujini99** [comment]
블루하와이에서

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/71487608/189539227-70a01562-1a7a-43b5-a0c8-ef2828343ad5.png">
![image](https://user-images.githubusercontent.com/71487608/189539234-175013ae-0e83-4af6-8d67-541a5b2099a5.png)
